name: Update Token Data

on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '1-59/5 * * * *'
    - cron: '2-59/5 * * * *'
    - cron: '3-59/5 * * * *'
    - cron: '4-59/5 * * * *'

jobs:
  update-token-data:
    runs-on: ubuntu-latest
    steps:
      - name: Call update-token-data API
        run: |
          curl -X POST https://dashboard.5318008.io/api/cron/update-token-data \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
